
import React, { useState } from 'react';
import { generateEducationalImage } from '../../services/geminiService';
import { Image as ImageIcon, Send, Loader2, Download } from 'lucide-react';

const PixelCanvas: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [imageData, setImageData] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setImageData(null);
    try {
      const result = await generateEducationalImage(prompt);
      setImageData(result);
    } catch (e) {
      alert("Failed to generate image. Please try a different prompt.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full dark:bg-slate-900 bg-white rounded-lg border dark:border-slate-700 border-slate-200 shadow-xl overflow-hidden">
      <div className="p-4 border-b dark:border-slate-700 border-slate-200 dark:bg-slate-800 bg-slate-50 flex items-center justify-between">
        <h2 className="font-bold dark:text-white text-slate-900 flex items-center gap-2">
            <ImageIcon className="text-pink-500" />
            PixelCanvas
        </h2>
        {imageData && (
            <a href={imageData} download="mindspark-gen.png" className="text-sm flex items-center gap-2 text-pink-600 hover:text-pink-700 font-medium">
                <Download size={16} /> Download
            </a>
        )}
      </div>

      <div className="flex-1 p-6 flex flex-col items-center justify-center dark:bg-slate-900 bg-slate-100 overflow-y-auto">
        {!imageData && !loading && (
          <div className="text-center dark:text-slate-500 text-slate-400">
            <ImageIcon size={64} className="mx-auto mb-4 opacity-30" />
            <p className="max-w-md mx-auto">
                Describe a diagram, historical scene, or scientific concept, and I'll draw it for you.
            </p>
            <p className="text-sm mt-2 italic">Try: "Structure of a plant cell" or "Ancient Roman Forum"</p>
          </div>
        )}
        
        {loading && (
          <div className="flex flex-col items-center">
            <Loader2 className="animate-spin text-pink-500 mb-4" size={48} />
            <p className="dark:text-slate-400 text-slate-500 animate-pulse">Generating masterpiece...</p>
          </div>
        )}

        {imageData && (
            <div className="relative w-full h-full min-h-[300px] flex items-center justify-center">
                <img 
                    src={imageData} 
                    alt="Generated by AI" 
                    className="max-w-full max-h-full object-contain rounded-lg shadow-2xl border-4 dark:border-slate-800 border-white" 
                />
            </div>
        )}
      </div>

      <div className="p-4 dark:bg-slate-800 bg-white border-t dark:border-slate-700 border-slate-200">
        <div className="flex items-center space-x-2">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
            placeholder="What should I draw?"
            className="flex-1 dark:bg-slate-900 bg-slate-50 border dark:border-slate-700 border-slate-300 dark:text-white text-slate-900 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-pink-500"
          />
          <button 
            onClick={handleGenerate}
            disabled={loading || !prompt.trim()}
            className="bg-pink-600 hover:bg-pink-700 text-white p-3 rounded-lg transition-colors disabled:opacity-50"
          >
            <Send size={20} />
          </button>
        </div>
      </div>
    </div>
  );
};

export default PixelCanvas;
